### ISSUE TITLE
滚动条引起的页面布局错位

### ISSUE THREAD

**Issue by 2dxgujun** [pexcn/Jekyll-Light#3]
你好，非常感谢你的博客模版。

我在使用过程发现几个问题，汇报一下：

1. 在内容比较少的Page页面滚动条没有显示时，左侧Sidebar会变宽（这个应该不是BUG）
2. 在阅读页，所有书加载完毕之后，Sidebar的背景会往右侧移一点点，在背景切换之后复原。
3. 在文章页，点击图片弹出图片盒子，页面会发生一些轻微的偏移（包括Sidebar）

不好意思，我有一点轻微的强迫症。。

**Comment by pexcn** [comment]
感谢反馈，其实这些问题我都知道，但我是小白。。无力修复。。。

**Comment by chris-zh** [comment]
。。。。。。无力修复点赞



Date: Thu, 29 Jan 2015 03:54:28 -0800

**Comment by pexcn** [comment]
。。。。。
